const express = require('express');
const router = express.Router();
const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } = require('docx');
const supabase = require('../lib/supabase');

router.post('/', async (req, res) => {
  const { sessionId, userId } = req.body;
  try {
    // Fetch session details
    const { data: session } = await supabase
      .from('sessions').select('title, created_at').eq('id', sessionId).single();

    // Fetch messages
    const { data: messages } = await supabase
      .from('messages').select('role, content, created_at')
      .eq('session_id', sessionId).order('created_at');

    if (!messages || messages.length === 0) {
      return res.status(400).json({ error: 'No messages found' });
    }

    const title = session?.title || 'AdvisoryHub Session';
    const date = new Date(session?.created_at || Date.now())
      .toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' });

    const children = [];

    // Title
    children.push(new Paragraph({
      text: title,
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 200 },
    }));

    // Date
    children.push(new Paragraph({
      children: [new TextRun({ text: 'AdvisoryHub  |  ' + date, color: '888888', size: 20 })],
      spacing: { after: 400 },
    }));

    // Messages
    for (const msg of messages) {
      const isUser = msg.role === 'user';

      // Role label
      children.push(new Paragraph({
        children: [new TextRun({
          text: isUser ? 'You' : 'AdvisoryHub',
          bold: true,
          size: 20,
          color: isUser ? '1a1a1a' : '0091a4',
        })],
        spacing: { before: 300, after: 100 },
      }));

      // Message content -- split by newlines to preserve paragraphs
      const lines = msg.content.split('\n');
      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed) continue;

        // Detect markdown headings
        if (trimmed.startsWith('### ')) {
          children.push(new Paragraph({
            text: trimmed.slice(4),
            heading: HeadingLevel.HEADING_3,
            spacing: { before: 200, after: 100 },
          }));
        } else if (trimmed.startsWith('## ')) {
          children.push(new Paragraph({
            text: trimmed.slice(3),
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 200, after: 100 },
          }));
        } else if (trimmed.startsWith('# ')) {
          children.push(new Paragraph({
            text: trimmed.slice(2),
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 200, after: 100 },
          }));
        } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
          children.push(new Paragraph({
            text: trimmed.slice(2),
            bullet: { level: 0 },
            spacing: { after: 80 },
          }));
        } else if (/^\d+\.\s/.test(trimmed)) {
          children.push(new Paragraph({
            text: trimmed.replace(/^\d+\.\s/, ''),
            numbering: { reference: 'default-numbering', level: 0 },
            spacing: { after: 80 },
          }));
        } else {
          // Remove markdown bold/italic for plain text
          const plain = trimmed.replace(/\*\*(.*?)\*\*/g, '$1').replace(/\*(.*?)\*/g, '$1');
          children.push(new Paragraph({
            children: [new TextRun({ text: plain, size: 24 })],
            spacing: { after: 120 },
          }));
        }
      }
    }

    // Footer
    children.push(new Paragraph({
      children: [new TextRun({ text: 'Generated by AdvisoryHub', color: 'aaaaaa', size: 18 })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 600 },
    }));

    const doc = new Document({
      sections: [{ children }],
      numbering: {
        config: [{
          reference: 'default-numbering',
          levels: [{ level: 0, format: 'decimal', text: '%1.', alignment: AlignmentType.START }],
        }],
      },
    });

    const buffer = await Packer.toBuffer(doc);
    const filename = title.replace(/[^a-z0-9]/gi, '-').toLowerCase().slice(0, 50) + '.docx';

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    res.setHeader('Content-Disposition', 'attachment; filename="' + filename + '"');
    res.send(buffer);
  } catch (err) {
    console.error('Generate file error:', err);
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;