// =============================================================================
// server/lib/buildWord.js
//
// Top-level Word document builder. Dispatches between two paths:
//
//   1. Template-driven: use a prepared template (e.g. Gold Coast briefing
//      note) via docxtemplater. Preserves branding, fonts, headers, footers.
//      Implementation in buildWordFromTemplate.js.
//
//   2. From-scratch: build a generic AdvisoryHub-styled document via docx-js.
//      Used when no template is requested. Useful for ad-hoc documents.
//
// The dispatch decision is made by the `template` field in the tool input.
// =============================================================================

const {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} = require('docx');
const { buildBriefingNote, TEMPLATES } = require('./buildWordFromTemplate');

/**
 * Top-level builder. Routes to template-based or scratch implementation
 * depending on input.template.
 *
 * @param {object} input    Tool input from create_word_document.
 * @returns {Promise<Buffer>}
 */
async function buildWordDocument(input) {
  const templateName = input && typeof input.template === 'string' ? input.template : null;

  if (templateName === 'briefing_note') {
    return buildBriefingNote(input);
  }

  // Unknown template name: fall back to scratch build but log a warning.
  if (templateName && !(templateName in TEMPLATES)) {
    console.warn(`buildWordDocument: unknown template '${templateName}', using scratch build`);
  }

  return buildScratchDocument(input);
}

// -----------------------------------------------------------------------------
// Scratch builder (no template) -- AdvisoryHub-styled generic document.
// -----------------------------------------------------------------------------

async function buildScratchDocument(input) {
  const safeInput = normaliseScratchInput(input);

  const date = new Date().toLocaleDateString('en-AU', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  const children = [];

  // Title
  children.push(
    new Paragraph({
      text: safeInput.title,
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 200 },
    })
  );

  // Subtitle (optional)
  if (safeInput.subtitle) {
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: safeInput.subtitle,
            size: 24,
            italics: true,
            color: '555555',
          }),
        ],
        spacing: { after: 200 },
      })
    );
  }

  // Header strip: organisation (if any) + date
  const headerParts = [];
  if (safeInput.organisation) headerParts.push(safeInput.organisation);
  headerParts.push(date);
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: headerParts.join('  |  '),
          color: '888888',
          size: 20,
        }),
      ],
      spacing: { after: 400 },
    })
  );

  // Sections
  for (const section of safeInput.sections) {
    if (section.heading) {
      const headingLevel =
        section.level === 1
          ? HeadingLevel.HEADING_1
          : section.level === 3
            ? HeadingLevel.HEADING_3
            : HeadingLevel.HEADING_2;
      children.push(
        new Paragraph({
          text: section.heading,
          heading: headingLevel,
          spacing: { before: 240, after: 120 },
        })
      );
    }

    for (const para of section.paragraphs) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: para, size: 22 })],
          spacing: { after: 160 },
        })
      );
    }

    for (const bullet of section.bullets) {
      children.push(
        new Paragraph({
          text: bullet,
          bullet: { level: 0 },
          spacing: { after: 80 },
        })
      );
    }
  }

  // Footer
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: 'Generated by AdvisoryHub',
          color: 'aaaaaa',
          size: 18,
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { before: 600 },
    })
  );

  const doc = new Document({
    sections: [{ children }],
  });

  return await Packer.toBuffer(doc);
}

/**
 * Sanitise + truncate a title into a filesystem-safe filename.
 */
function safeFilename(title) {
  const base = (title || 'document')
    .replace(/[^a-z0-9]/gi, '-')
    .toLowerCase()
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 50) || 'document';
  const stamp = Date.now().toString(36);
  return `${base}-${stamp}.docx`;
}

// -----------------------------------------------------------------------------
// Defensive input coercion for the scratch path.
// (The template path has its own coercion in buildWordFromTemplate.js.)
// -----------------------------------------------------------------------------

function normaliseScratchInput(raw) {
  const input = raw && typeof raw === 'object' ? raw : {};
  const title = typeof input.title === 'string' && input.title.trim()
    ? input.title.trim()
    : 'Untitled Document';
  const subtitle = typeof input.subtitle === 'string' ? input.subtitle.trim() : '';
  const organisation = typeof input.organisation === 'string' ? input.organisation.trim() : '';

  const rawSections = Array.isArray(input.sections) ? input.sections : [];
  const sections = rawSections.map(normaliseSection).filter(s => s !== null);

  if (sections.length === 0) {
    sections.push({
      heading: 'Content',
      level: 2,
      paragraphs: ['(No content was generated.)'],
      bullets: [],
    });
  }

  return { title, subtitle, organisation, sections };
}

function normaliseSection(raw) {
  if (!raw || typeof raw !== 'object') return null;
  const heading = typeof raw.heading === 'string' ? raw.heading.trim() : '';
  const levelRaw = Number(raw.level);
  const level = (levelRaw === 1 || levelRaw === 2 || levelRaw === 3) ? levelRaw : 2;
  const paragraphs = Array.isArray(raw.paragraphs)
    ? raw.paragraphs
        .filter(p => typeof p === 'string' && p.trim().length > 0)
        .map(p => p.trim())
    : [];
  const bullets = Array.isArray(raw.bullets)
    ? raw.bullets
        .filter(b => typeof b === 'string' && b.trim().length > 0)
        .map(b => b.trim())
    : [];

  if (!heading && paragraphs.length === 0 && bullets.length === 0) return null;

  return { heading, level, paragraphs, bullets };
}

const WORD_MIME =
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document';

module.exports = { buildWordDocument, safeFilename, WORD_MIME };
