// =============================================================================
// server/lib/buildWord.js
//
// Builds a Microsoft Word (.docx) buffer from structured input supplied by
// Claude via the create_word_document tool call.
//
// Visual style intentionally matches server/routes/generateFile.js (the
// session transcript export) so AI-authored documents and transcript exports
// feel like they belong to the same product.
//
// Stage 1 scope: title, optional subtitle, organisation+date strip, section
// headings (3 levels), body paragraphs, bullet lists, footer. No tables, no
// inline rich text, no styling overrides. Tables come in a follow-on card.
// =============================================================================

const {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} = require('docx');

/**
 * @typedef {object} WordSection
 * @property {string}   heading         Section heading text.
 * @property {1|2|3}    level           Heading level. 2 by default.
 * @property {string[]} [paragraphs]    Plain text body paragraphs.
 * @property {string[]} [bullets]       Plain text bullet list.
 */

/**
 * @typedef {object} WordInput
 * @property {string}        title         Document title.
 * @property {string}        [subtitle]    Optional subtitle.
 * @property {string}        [organisation] Optional organisation name shown in header.
 * @property {WordSection[]} sections      Document body, organised into sections.
 */

/**
 * Build a Word document buffer from structured input.
 *
 * Defensively coerces input. If the tool call has missing or malformed
 * fields, the build still produces a sensible document rather than throwing.
 *
 * @param {WordInput} input
 * @returns {Promise<Buffer>}
 */
async function buildWordDocument(input) {
  const safeInput = normaliseInput(input);

  const date = new Date().toLocaleDateString('en-AU', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  const children = [];

  // Title
  children.push(
    new Paragraph({
      text: safeInput.title,
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 200 },
    })
  );

  // Subtitle (optional)
  if (safeInput.subtitle) {
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: safeInput.subtitle,
            size: 24,
            italics: true,
            color: '555555',
          }),
        ],
        spacing: { after: 200 },
      })
    );
  }

  // Header strip: organisation (if any) + date
  const headerParts = [];
  if (safeInput.organisation) headerParts.push(safeInput.organisation);
  headerParts.push(date);
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: headerParts.join('  |  '),
          color: '888888',
          size: 20,
        }),
      ],
      spacing: { after: 400 },
    })
  );

  // Sections
  for (const section of safeInput.sections) {
    if (section.heading) {
      const headingLevel =
        section.level === 1
          ? HeadingLevel.HEADING_1
          : section.level === 3
            ? HeadingLevel.HEADING_3
            : HeadingLevel.HEADING_2;
      children.push(
        new Paragraph({
          text: section.heading,
          heading: headingLevel,
          spacing: { before: 240, after: 120 },
        })
      );
    }

    for (const para of section.paragraphs) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: para, size: 22 })],
          spacing: { after: 160 },
        })
      );
    }

    for (const bullet of section.bullets) {
      children.push(
        new Paragraph({
          text: bullet,
          bullet: { level: 0 },
          spacing: { after: 80 },
        })
      );
    }
  }

  // Footer
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: 'Generated by AdvisoryHub',
          color: 'aaaaaa',
          size: 18,
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { before: 600 },
    })
  );

  const doc = new Document({
    sections: [{ children }],
  });

  return await Packer.toBuffer(doc);
}

/**
 * Sanitise + truncate a title into a filesystem-safe filename.
 * Pattern matches server/routes/generateFile.js for consistency.
 *
 * @param {string} title
 * @returns {string} filename ending in .docx
 */
function safeFilename(title) {
  const base = (title || 'document')
    .replace(/[^a-z0-9]/gi, '-')
    .toLowerCase()
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 50) || 'document';
  // Append a short timestamp so retries don't collide. Easier than
  // generating UUIDs and still readable.
  const stamp = Date.now().toString(36);
  return `${base}-${stamp}.docx`;
}

// -----------------------------------------------------------------------------
// Defensive input coercion. Claude's tool calls are usually well-formed, but
// one missing field shouldn't crash the build.
// -----------------------------------------------------------------------------
function normaliseInput(raw) {
  const input = raw && typeof raw === 'object' ? raw : {};
  const title = typeof input.title === 'string' && input.title.trim()
    ? input.title.trim()
    : 'Untitled Document';
  const subtitle = typeof input.subtitle === 'string' ? input.subtitle.trim() : '';
  const organisation = typeof input.organisation === 'string' ? input.organisation.trim() : '';

  const rawSections = Array.isArray(input.sections) ? input.sections : [];
  const sections = rawSections.map(normaliseSection).filter(s => s !== null);

  // If the AI somehow produced a doc with no usable sections, give it one
  // empty placeholder so the file still opens cleanly.
  if (sections.length === 0) {
    sections.push({
      heading: 'Content',
      level: 2,
      paragraphs: ['(No content was generated.)'],
      bullets: [],
    });
  }

  return { title, subtitle, organisation, sections };
}

function normaliseSection(raw) {
  if (!raw || typeof raw !== 'object') return null;
  const heading = typeof raw.heading === 'string' ? raw.heading.trim() : '';
  const levelRaw = Number(raw.level);
  const level = (levelRaw === 1 || levelRaw === 2 || levelRaw === 3) ? levelRaw : 2;
  const paragraphs = Array.isArray(raw.paragraphs)
    ? raw.paragraphs
        .filter(p => typeof p === 'string' && p.trim().length > 0)
        .map(p => p.trim())
    : [];
  const bullets = Array.isArray(raw.bullets)
    ? raw.bullets
        .filter(b => typeof b === 'string' && b.trim().length > 0)
        .map(b => b.trim())
    : [];

  // A section with no heading and no body is meaningless. Drop it.
  if (!heading && paragraphs.length === 0 && bullets.length === 0) return null;

  return { heading, level, paragraphs, bullets };
}

const WORD_MIME =
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document';

module.exports = { buildWordDocument, safeFilename, WORD_MIME };
